/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/mobistack/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["authMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mobistack/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["authLogout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mobistack/billing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["billingOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mobistack/billing/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createBillingOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mobistack/billing/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["verifyBillingPayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mobistack/admin/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminWorkspaces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mobistack/admin/feature-flags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminFeatureFlags"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mobistack/admin/billing/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminBillingOrders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mobistack/admin/billing/revenue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminRevenue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mobistack/admin/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminPlans"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mobistack/admin/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminLive"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mobistack/admin/support": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminSupport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mobistack/admin/app-releases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminAppReleases"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mobistack/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listWorkspaces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mobistack/system/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["systemHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AuthenticatedUser: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            shopId?: string;
            shopName?: string;
            /** Format: uuid */
            workspaceId?: string;
            workspaceName?: string;
            fullName?: string;
            email?: string;
            phone?: string;
            avatarUrl?: string;
            roles?: string[];
            permissions?: string[];
            systemAdmin?: boolean;
            emailVerified?: boolean;
            phoneVerified?: boolean;
            paymentRequired?: boolean;
            catalogOnly?: boolean;
            features?: string[];
            planCode?: string;
            planName?: string;
            /** Format: date-time */
            periodEnd?: string;
        };
        PlanCard: {
            /** Format: uuid */
            id?: string;
            code?: string;
            name?: string;
            description?: string;
            amount?: number;
            currency?: string;
            interval?: string;
            sortOrder?: number;
            active?: boolean;
            features?: string[];
            priceCode?: string;
        };
        SubscriptionCard: {
            planCode?: string;
            planName?: string;
            status?: string;
            /** Format: date-time */
            periodEnd?: string;
            features?: string[];
        };
        ScreenCard: {
            included?: number;
            extra?: number;
            subscribed?: number;
            seats?: number;
            inUse?: number;
            live?: boolean;
            /** Format: date-time */
            periodEnd?: string;
            amount?: number;
            renewAmount?: number;
            currency?: string;
            priceCode?: string;
            interval?: string;
        };
        PaymentReceipt: {
            /** Format: uuid */
            id?: string;
            planName?: string;
            priceCode?: string;
            amount?: number;
            currency?: string;
            status?: string;
            /** Format: date-time */
            paidAt?: string;
        };
        BillingOverview: {
            plans?: components["schemas"]["PlanCard"][];
            subscription?: components["schemas"]["SubscriptionCard"];
            recentPayments?: components["schemas"]["PaymentReceipt"][];
            screens?: components["schemas"]["ScreenCard"];
            razorpayKeyId?: string;
            razorpayEnabled?: boolean;
            paymentRequired?: boolean;
        };
        CheckoutOrderResponse: {
            /** Format: uuid */
            id?: string;
            order_id?: string;
            /** Format: int64 */
            amount?: number;
            currency?: string;
            keyId?: string;
            priceCode?: string;
            gateway?: string;
        };
        VerifyPaymentRequest: {
            razorpayOrderId?: string;
            razorpayPaymentId?: string;
            razorpaySignature?: string;
        };
        WorkspaceAdminCard: {
            /** Format: uuid */
            id?: string;
            name?: string;
            city?: string;
            active?: boolean;
            /** Format: int64 */
            members?: number;
            extraScreens?: number;
            screenSeats?: number;
        };
        FlagCard: {
            code?: string;
            enabled?: boolean;
        };
        AdminPayment: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            shopId?: string;
            shopName?: string;
            priceCode?: string;
            amount?: number;
            currency?: string;
            status?: string;
            gateway?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            paidAt?: string;
        };
        RevenueSnapshot: {
            capturedTotal?: number;
            pendingTotal?: number;
            capturedCount?: number;
            pendingCount?: number;
            failedCount?: number;
            currency?: string;
            /** Format: date-time */
            asOf?: string;
        };
        AdminLiveUser: {
            /** Format: uuid */
            userId?: string;
            fullName?: string;
            email?: string;
            shopName?: string;
            deviceId?: string;
            platform?: string;
            appVersion?: string;
            ipAddress?: string;
            /** Format: date-time */
            seenAt?: string;
        };
        AdminSupportMessage: {
            /** Format: uuid */
            id?: string;
            authorType?: string;
            body?: string;
        };
        AdminSupportTicket: {
            /** Format: uuid */
            id?: string;
            subject?: string;
            status?: string;
            userName?: string;
            /** Format: date-time */
            lastMessageAt?: string;
            messages?: components["schemas"]["AdminSupportMessage"][];
        };
        AdminAppRelease: {
            platform?: string;
            minNativeBuild?: number;
            latestNativeBuild?: number;
            forceNativeUpdate?: boolean;
            otaChannel?: string;
            storeUrl?: string;
            notes?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    authMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthenticatedUser"];
                };
            };
        };
    };
    authLogout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    billingOverview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BillingOverview"];
                };
            };
        };
    };
    createBillingOrder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CheckoutOrderResponse"];
                };
            };
        };
    };
    verifyBillingPayment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["VerifyPaymentRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    adminWorkspaces: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WorkspaceAdminCard"][];
                };
            };
        };
    };
    adminFeatureFlags: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FlagCard"][];
                };
            };
        };
    };
    adminBillingOrders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminPayment"][];
                };
            };
        };
    };
    adminRevenue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RevenueSnapshot"];
                };
            };
        };
    };
    adminPlans: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PlanCard"][];
                };
            };
        };
    };
    adminLive: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminLiveUser"][];
                };
            };
        };
    };
    adminSupport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminSupportTicket"][];
                };
            };
        };
    };
    adminAppReleases: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminAppRelease"][];
                };
            };
        };
    };
    listWorkspaces: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    systemHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
